# Stages

(COURSE_OVERVIEW,
 COURSE_OPTIONS,
 REFFERENCE_OPTIONS,
 EXAM_OPTIONS,
 LECTURES_LIST,
 RECIEVE_COURSE_REF,
 RECIEVE_COURSE_EXAM,
 RECIEVIE_LECTURE_FILE,
 RECIEVE_NAME_SYMBOL,
 LECTURE_OPTIONS,
 PERFORM_ACTION,
 RECIEVE_LECTURE_NUMBER,
 CONFIRM_COURSE_DELETION,
 RECIEVE_NEW_COURSE,
 FILE_OPTIONS,
 REFFERENCES_LIST,
 EXAMS_LIST) = range(17)