"""empty message

Revision ID: 3cc389515d67
Revises: aa938831b75c
Create Date: 2021-09-03 00:35:31.397085

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '3cc389515d67'
down_revision = 'aa938831b75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'name', new_column_name='ar_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'ar_name', new_column_name='name')

    # ### end Alembic commands ###
