"""empty message

Revision ID: 3cd23fe49236
Revises: ffd2d5a84092
Create Date: 2021-10-24 01:44:39.260628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd23fe49236'
down_revision = 'ffd2d5a84092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('file_id', sa.String(length=300), nullable=True),
    sa.Column('file_unique_id', sa.String(length=300), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_photos_exam_id_exams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_documents_exam_id_exams'), 'exams', ['exam_id'], ['id'])

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=300), nullable=True))
        batch_op.drop_column('file_id')
        batch_op.drop_column('file_unique_id')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_name')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=300), nullable=False))
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_unique_id', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('file_id', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_exam_id_exams'), type_='foreignkey')
        batch_op.drop_column('exam_id')


    op.drop_table('photos')
    # ### end Alembic commands ###
