"""empty message

Revision ID: 3fd80a5c9d9f
Revises: 5aac2bdfd455
Create Date: 2021-09-03 21:49:55.121106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd80a5c9d9f'
down_revision = '5aac2bdfd455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('en_course_symbol', sa.String(length=50), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'en_course_symbol')
    # ### end Alembic commands ###
