"""empty message

Revision ID: 501fcb5eb349
Revises: 3cd23fe49236
Create Date: 2022-02-12 00:08:41.524096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501fcb5eb349'
down_revision = '3cd23fe49236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semesters'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_semester_id_semesters'), 'semesters', ['semester_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_semester_id_semesters'), type_='foreignkey')
        batch_op.drop_column('semester_id')

    op.drop_table('semesters')
    # ### end Alembic commands ###
