"""empty message

Revision ID: 5aac2bdfd455
Revises: 3cc389515d67
Create Date: 2021-09-03 02:35:10.322348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aac2bdfd455'
down_revision = '3cc389515d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('en_name', sa.String(length=100), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'en_name')
    # ### end Alembic commands ###
