"""empty message

Revision ID: 806513400cf6
Revises: bdaf7ca21528
Create Date: 2022-02-26 16:39:13.513401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806513400cf6'
down_revision = 'bdaf7ca21528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_data')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_chat_data_chat_id'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('new_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_data')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_data_user_id'))
    )
    op.drop_table('persistence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('persistence',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.CheckConstraint("id = '18F9fe34ae49Z4'", name='ck_persistence_only_one_row'),
    sa.PrimaryKeyConstraint('id', name='pk_persistence')
    )
    op.drop_table('user_data')
    op.drop_table('conversations')
    op.drop_table('chat_data')
    # ### end Alembic commands ###
