"""empty message

Revision ID: 949c1f5e0487
Revises: decedd053c98
Create Date: 2022-08-19 19:14:12.080103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949c1f5e0487'
down_revision = 'decedd053c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True, server_default="1"))

    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True, server_default="1"))

    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True, server_default="1"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.drop_column('published')

    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_column('published')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###
