"""empty message

Revision ID: 9581aa96a4f5
Revises: 501fcb5eb349
Create Date: 2022-02-14 18:48:52.014363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9581aa96a4f5'
down_revision = '501fcb5eb349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_semester',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("id = '1G3S34OS29Z4'", name=op.f('ck_current_semester_only_one_row')),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_current_semester_semester_id_semesters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_current_semester'))
    )

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), nullable=True))


    op.drop_table('current_semester')
    # ### end Alembic commands ###
