"""empty message

Revision ID: b3481ed72ab5
Revises: 8e9c1b692420
Create Date: 2022-11-07 17:41:16.105309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3481ed72ab5'
down_revision = '8e9c1b692420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('file_id', sa.String(length=300), nullable=True),
    sa.Column('file_unique_id', sa.String(length=300), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_sheets_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheets'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheets')
    # ### end Alembic commands ###
