"""empty message

Revision ID: bdaf7ca21528
Revises: 9581aa96a4f5
Create Date: 2022-02-25 15:54:05.893262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdaf7ca21528'
down_revision = '9581aa96a4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistence',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.CheckConstraint("id = '18F9fe34ae49Z4'", name=op.f('ck_persistence_only_one_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persistence'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('persistence')
    # ### end Alembic commands ###
