"""empty message

Revision ID: ffd2d5a84092
Revises: 093e6ef4bdba
Create Date: 2021-09-11 16:56:34.082327

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ffd2d5a84092'
down_revision = '093e6ef4bdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.Integer(), nullable=True, server_default=''))
        batch_op.add_column(sa.Column('subscribed', sa.Boolean(), nullable=True, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscribed')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
