# show global note - boolean
SHOW_GLOBAL_NOTE = False

# Navigation stages

( RECEIVE_ENTRY_NOTIFICATIONS,
 NOTIFIED_LECTURE_OPTIONS,
 NOTIFIED_LAB_OPTIONS,
 NOTIFIED_TUTORIAL_OPTIONS,
) = range(4)

LECTURE_NOTIFICATION = 'LECTURE_NOTIFICATION'
RECIEVE_LECTURES_NOTIFICATIONS = 'RECIEVE_LECTURES_NOTIFICATIONS'

LAB_NOTIFICATION = 'LAB_NOTIFICATION'
RECIEVE_LABS_NOTIFICATIONS = 'RECIEVE_LABS_NOTIFICATIONS'

TUTORIAL_NOTIFICATION = 'TUTORIAL_NOTIFICATION'
RECIEVE_TUTORIALS_NOTIFICATIONS = 'RECIEVE_TUTORIALS_NOTIFICATIONS'

ASSIGNMENT_NOTIFICATION = 'ASSIGNMENT_NOTIFICATION'
RECIEVE_ASSIGNMENTS_NOTIFICATIONS = 'RECIEVE_ASSIGNMENTS_NOTIFICATIONS'

DISABLE_ALL = 'DISABEL_ALL'


NOTIFICATIONS_SETTINGS = 'NOTIFICATIONS_SETTINGS'

NOTIFIED_LECTURE = 'NOTIFIED_LECTURE'

NOTIFIED_LAB = 'NOTIFIED_LAB'

NOTIFIED_TUTORIAL = 'NOTIFIED_TUTORIAL'

SEND_NOTIFIED_ASSIGNMENT = 'SEND_NOTIFIED_ASSIGNMENT'

LECTURE_NOTIFICATION_MESSAGE = 'LECTURE_NOTIFICATION_MESSAGE'
LAB_NOTIFICATION_MESSAGE = 'LAB_NOTIFICATION_MESSAGE'
TUTORIAL_NOTIFICATION_MESSAGE = 'TUTORIAL_NOTIFICATION_MESSAGE'
