# show global note - boolean
SHOW_GLOBAL_NOTE = False

# Navigation stages

( COURSE_OVERVIEW,
 ARCHIVED_SEMESTER,
 STAGE_TWO,
 STAGE_THREE,
 STAGE_FOURE,
 STAGE_FIVE, 
 SEMESTER_LIST) = range(7)

LECTURE_NOTIFICATION = 'LECTURE_NOTIFICATION'
RECIEVE_LECTURES_NOTIFICATIONS = 'RECIEVE_LECTURES_NOTIFICATIONS'

LAB_NOTIFICATION = 'LAB_NOTIFICATION'
RECIEVE_LABS_NOTIFICATIONS = 'RECIEVE_LABS_NOTIFICATIONS'

ASSIGNMENT_NOTIFICATION = 'ASSIGNMENT_NOTIFICATION'
RECIEVE_ASSIGNMENTS_NOTIFICATIONS = 'RECIEVE_ASSIGNMENTS_NOTIFICATIONS'

DISABLE_ALL = 'DISABEL_ALL'

RECEIVE_ENTRY_NOTIFICATIONS = 'SET_ENTRY_NOTIFICATIONS'

NOTIFICATIONS_SETTINGS = 'NOTIFICATIONS_SETTINGS'

NOTIFIED_LECTURE = 'NOTIFIED_LECTURE'
SEND_NOTIFIED_LECTURE = 'SEND_NOTIFIED_LECTURE'

NOTIFIED_LAB = 'NOTIFIED_LAB'
SEND_NOTIFIED_LAB = 'SEND_NOTIFIED_LAB'

SEND_NOTIFIED_ASSIGNMENT = 'SEND_NOTIFIED_ASSIGNMENT'

ENTRY_POINTS = 'ENTRY_POINTS'

LECTURE_NOTIFICATION_MESSAGE = 'LECTURE_NOTIFICATION_MESSAGE'
LAB_NOTIFICATION_MESSAGE = 'LAB_NOTIFICATION_MESSAGE'

NOTIFIED_LECTURE_OPTIONS = 'NOTIFIED_LECTURE_OPTIONS'
NOTIFIED_LAB_OPTIONS = 'NOTIFIED_LAB_OPTIONS'